export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const SEND_APPLICATION = 'SEND_APPLICATION';
export const LIKE_UNLIKE_PRODUCT = 'LIKE_UNLIKE_PRODUCT';
export const SUCCESSFULLY_SIGNED = 'SUCCESSFULLY_SIGNED';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const DISPLAY_ERROR_MESSAGE = 'DISPLAY_ERROR_MESSAGE';


